name: Bug Reports
description: For reporting known and reproducible issues with the software.
body:
  - type: markdown
    attributes:
      value: |
        Bug reports should only be used for reporting issues with how the software works. For installation help or dependency debugging, please start a [discussion](https://github.com/Evodactyl/evodactyl-panel/discussions).

  - type: textarea
    attributes:
      label: Current Behavior
      description: Please provide a clear & concise description of the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please be as detailed as possible when providing steps to reproduce. Failure to provide steps will result in this issue being closed.
    validations:
      required: true

  - type: input
    id: panel-version
    attributes:
      label: Evodactyl Panel Version
      description: Commit hash or release tag (latest is not a version).
      placeholder: 2.0.0
    validations:
      required: true

  - type: input
    id: wings-version
    attributes:
      label: Wings Version
      description: Version number of your Wings (latest is not a version).
      placeholder: 1.11.13
    validations:
      required: true

  - type: input
    id: egg-details
    attributes:
      label: Games and/or Eggs Affected
      description: Please include the specific game(s) or egg(s) you are running into this bug with.
      placeholder: Minecraft (Paper), Minecraft (Forge)

  - type: input
    id: docker-image
    attributes:
      label: Docker Image
      description: The specific Docker image you are using for the game(s) above.
      placeholder: ghcr.io/pterodactyl/yolks:java_17

  - type: textarea
    id: panel-logs
    attributes:
      label: Error Logs
      description: |
        Paste any relevant panel / Wings logs here. For Wings: `sudo wings diagnostics`.
      render: bash
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search here](https://github.com/Evodactyl/evodactyl-panel/issues) first.
      options:
        - label: I have searched the existing issues before opening this issue.
          required: true
