blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Evodactyl/evodactyl-panel/discussions
    about: The preferred method for getting help with Evodactyl or proposing new features.
  - name: Documentation
    url: https://evodactyl.github.io/panel/
    about: Installation, configuration, and API reference.
